wordList = [  # GPT4
    "algorithm",
    "binary",
    "calibration",
    "camera",
    "depth",
    "detection",
    "encoder",
    "estimation",
    "finger",
    "frame",
    "gesture",
    "grasp",
    "hardware",
    "haptics",
    "infrared",
    "interaction",
    "joystick",
    "joint",
    "keystroke",
    "laser",
    "localization",
    "manipulation",
    "motion",
    "network",
    "occlusion",
    "optical",
    "palm",
    "position",
    "query",
    "realtime",
    "recognition",
    "sensor",
    "stereo",
    "tracking",
    "touch",
    "ultrasound",
    "user",
    "virtual",
    "viewport",
    "webcam",
    "wrist",
    "zoom"
]

hangman_words = [
    "Enlightenment",
    "Accomplishment",
    "Constitution",
    "Refurbishment",
    "Exceptionally",
    "Caterpillar",
    "Zoologist",
    "Volcano",
    "Quarterback",
    "Microscope",
    "Jackhammer",
    "Hypothesis",
    "Guacamole",
    "Whirlpool",
    "Xenophobia",
    "Wavelength",
    "Vindictive",
    "Unquestionable",
    "Tranquilizer",
    "Symphony",
    "Rhythmically",
    "Quintessential",
    "Pyromania",
    "Overzealous",
    "Nebulous",
    "Miscellaneous",
    "Labyrinth",
    "Kaleidoscope",
    "Juxtaposition",
    "Hummingbird",
    "Inconsequential",
    "Unforgettable",
    "Subterranean",
    "Synchronized",
    "Rehabilitation",
    "Quarantine",
    "Parallelogram",
    "Misdemeanor",
    "Lumberjack",
    "Knowledgeable",
    "Intercontinental",
    "Galaxy",
    "Fisherman",
    "Endangered",
    "Dishonesty",
    "Cappuccino",
    "Brainstorm",
    "Avalanche",
    "Anticipation",
    "Unprecedented",
    "Surveillance",
    "Revolutionary",
    "Procrastination",
    "Oblivious",
    "Nostalgia",
    "Machinery",
    "Laughter",
    "Kilogram",
    "Infrastructure",
    "Hippopotamus",
    "Gargantuan",
    "Flabbergasted",
    "Exponential",
    "Discombobulate",
    "Cryptocurrency",
    "Boulevard",
    "Appreciation",
    "Algorithm",
    "Zucchini",
    "Yacht",
    "Xylophone",
    "Wholesome",
    "Vigilante",
    "Unanimous",
    "Territory",
    "Spectacular",
    "Renaissance",
    "Quicksand",
    "Pterodactyl",
    "Optimistic",
    "Neighborhood",
    "Misunderstand",
    "Logistics",
    "Kaleidoscope",
    "Jumpstart",
    "Invincible",
    "Hallucination",
    "Gratitude",
    "Fascinating",
    "Extraordinary",
    "Doppelganger",
    "Collaborate",
    "Blacksmith",
    "Ambidextrous",
    "Accordion",
    "Zigzag",
    "Yodel",
    "Xenon",
    "Wrinkle",
    "Vortex",
    "Underestimate",
    "Thunderstorm",
    "Semaphore",
    "Radiant",
    "Quadrilateral",
    "Photosynthesis",
    "Nomenclature",
    "Metamorphosis",
    "Leprechaun",
    "Knuckle",
    "Irresistible",
    "Hydrogen",
    "Graffiti",
    "Fingerprint",
    "Exhilarating",
    "Disintegrate",
    "Chameleon",
    "Bittersweet",
    "Astronaut",
    "Alphabetical",
    "Zephyr",
    "Yachtsman",
    "Xenophobic",
    "Watermelon",
    "Vegetable",
    "Unforgettable",
    "Tsunami",
    "Silhouette",
    "Responsibility",
    "Quadruple",
    "Pulverize",
    "Outrageous",
    "Nightmare",
    "Mysterious",
    "Ludicrous",
    "Kindergarten",
    "Inconceivable",
    "Hyperventilate",
    "Gossip",
    "Flashlight",
    "Exceptional",
    "Dramatic",
    "Compliment",
    "Blizzard",
    "Arachnophobia",
    "Apostrophe",
    "Zookeeper",
    "Yearbook",
    "Xerox",
    "Witchcraft",
    "Ventilator",
    "Unnecessary",
    "Technique",
    "Sasquatch",
    "Resurrection",
    "Quintuplets",
    "Punctuation",
    "Observatory",
    "Narcissist",
    "Multilingual",
    "Landscape",
    "Kaleidoscope",
    "Insignificant",
    "Hydrangea",
    "Gargoyle",
    "Flabbergast",
    "Extravagant",
    "Discrimination",
    "Consequence",
    "Bibliography",
    "Astronomy",
    "Archaeology"
]


stages = [
    '''
   +
   |
   |
   |
   |
  ===
    ''',

    '''
  +---+
  |
  |
  |
  |
  ===
    ''',

    '''
  +---+
  |   O
  |
  |
  |
  ===
    ''',

    '''
  +---+
  |   O
  |   |
  |
  |
  ===
    ''',

    '''
  +---+
  |   O
  |  /|
  |
  |
  ===
    ''',

    '''
  +---+
  |   O
  |  /|\
  |
  |
  ===
    ''',

    '''
  +---+
  |   O
  |  /|\
  |  /
  |
  ===
    ''',

    '''
  +---+
  |   O
  |  /|\
  |  / \
  |
  ===
    '''
]